name: Build

on:
  push:
    branches: [ release-4.3 ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup Pusher App credentials
      env:
        APP_ID: ${{ secrets.CI_APP_ID }}
        APP_KEY: ${{ secrets.CI_APP_KEY }}
        APP_SECRET: ${{ secrets.CI_APP_SECRET }}
        APP_CLUSTER: ${{ secrets.CI_APP_CLUSTER }}
      run: |
        echo "{
        `"AppId`": `"$env:APP_ID`",
        `"AppKey`": `"$env:APP_KEY`",
        `"AppSecret`": `"$env:APP_SECRET`",
        `"HttpHost`": `"api-$env:APP_CLUSTER.pusher.com`",
        `"WebSocketHost`": `"ws-${env:APP_CLUSTER}.pusher.com`"
        }" > AppConfig.test.json

    - name: Setup MS Build
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1
    - name: Restore dependencies
      run: nuget restore pusher-dotnet-server.sln
    - name: Build
      run: msbuild /p:deterministic=true /p:msbuildArchitecture=x64 /p:configuration=release pusher-dotnet-server.sln
    - name: Test
      run: vstest.console.exe ".\PusherServer.Tests\bin\Release\net45\PusherServer.Tests.dll" /TestAdapterPath:".\PusherServer.Tests\bin\Release\net45\"
