name: Publish

on:
  push:
    branches: [ github-actions ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: nuget restore pusher-dotnet-server.sln
    - name: Pack
      run: dotnet pack --no-restore -c Release pusher-dotnet-server.sln
